# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1023, 642)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 1011, 631))
        self.tabWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(86, 72, 128, 85), stop:1 rgba(255, 255, 255, 255));")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 151, 16))
        self.label_3.setObjectName("label_3")
        self.verigoster = QtWidgets.QTableWidget(self.tab_5)
        self.verigoster.setGeometry(QtCore.QRect(10, 70, 841, 401))
        self.verigoster.setStyleSheet("background-color: rgb(186, 186, 186);")
        self.verigoster.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.verigoster.setObjectName("verigoster")
        self.verigoster.setColumnCount(0)
        self.verigoster.setRowCount(0)
        self.btnyukle = QtWidgets.QPushButton(self.tab_5)
        self.btnyukle.setGeometry(QtCore.QRect(20, 10, 181, 31))
        self.btnyukle.setStyleSheet("")
        self.btnyukle.setObjectName("btnyukle")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.btnyukle_2 = QtWidgets.QPushButton(self.tab)
        self.btnyukle_2.setGeometry(QtCore.QRect(20, 10, 181, 31))
        self.btnyukle_2.setStyleSheet("")
        self.btnyukle_2.setObjectName("btnyukle_2")
        self.verigoster_2 = QtWidgets.QTableWidget(self.tab)
        self.verigoster_2.setGeometry(QtCore.QRect(10, 50, 841, 401))
        self.verigoster_2.setStyleSheet("background-color: rgb(186, 186, 186);")
        self.verigoster_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.verigoster_2.setObjectName("verigoster_2")
        self.verigoster_2.setColumnCount(0)
        self.verigoster_2.setRowCount(0)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.btnveribol = QtWidgets.QPushButton(self.tab_2)
        self.btnveribol.setGeometry(QtCore.QRect(10, 10, 231, 31))
        self.btnveribol.setStyleSheet("")
        self.btnveribol.setObjectName("btnveribol")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.list_y_train = QtWidgets.QTableWidget(self.tab_3)
        self.list_y_train.setGeometry(QtCore.QRect(620, 90, 221, 111))
        self.list_y_train.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_y_train.setObjectName("list_y_train")
        self.list_y_train.setColumnCount(0)
        self.list_y_train.setRowCount(0)
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(620, 70, 71, 16))
        self.label_27.setObjectName("label_27")
        self.list_y_test = QtWidgets.QTableWidget(self.tab_3)
        self.list_y_test.setGeometry(QtCore.QRect(620, 260, 221, 111))
        self.list_y_test.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_y_test.setObjectName("list_y_test")
        self.list_y_test.setColumnCount(0)
        self.list_y_test.setRowCount(0)
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        self.label_24.setGeometry(QtCore.QRect(630, 240, 71, 16))
        self.label_24.setObjectName("label_24")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(330, 240, 81, 16))
        self.label_11.setObjectName("label_11")
        self.list_x_train = QtWidgets.QTableWidget(self.tab_3)
        self.list_x_train.setGeometry(QtCore.QRect(330, 90, 221, 111))
        self.list_x_train.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_x_train.setObjectName("list_x_train")
        self.list_x_train.setColumnCount(0)
        self.list_x_train.setRowCount(0)
        self.list_x_test = QtWidgets.QTableWidget(self.tab_3)
        self.list_x_test.setGeometry(QtCore.QRect(330, 260, 221, 111))
        self.list_x_test.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_x_test.setObjectName("list_x_test")
        self.list_x_test.setColumnCount(0)
        self.list_x_test.setRowCount(0)
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(330, 70, 91, 16))
        self.label_14.setObjectName("label_14")
        self.verigoster_3 = QtWidgets.QTableWidget(self.tab_3)
        self.verigoster_3.setGeometry(QtCore.QRect(10, 70, 291, 461))
        self.verigoster_3.setStyleSheet("background-color: rgb(186, 186, 186);")
        self.verigoster_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.verigoster_3.setObjectName("verigoster_3")
        self.verigoster_3.setColumnCount(0)
        self.verigoster_3.setRowCount(0)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 151, 16))
        self.label_4.setObjectName("label_4")
        self.list_y_train.raise_()
        self.label_27.raise_()
        self.list_y_train.raise_()
        self.label_27.raise_()
        self.list_y_test.raise_()
        self.label_24.raise_()
        self.label_11.raise_()
        self.list_x_train.raise_()
        self.list_x_test.raise_()
        self.label_14.raise_()
        self.verigoster_3.raise_()
        self.label_4.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.list_y_test_2 = QtWidgets.QTableWidget(self.tab_4)
        self.list_y_test_2.setGeometry(QtCore.QRect(620, 220, 221, 111))
        self.list_y_test_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_y_test_2.setObjectName("list_y_test_2")
        self.list_y_test_2.setColumnCount(0)
        self.list_y_test_2.setRowCount(0)
        self.list_x_train_2 = QtWidgets.QTableWidget(self.tab_4)
        self.list_x_train_2.setGeometry(QtCore.QRect(330, 50, 221, 111))
        self.list_x_train_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_x_train_2.setObjectName("list_x_train_2")
        self.list_x_train_2.setColumnCount(0)
        self.list_x_train_2.setRowCount(0)
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(630, 200, 71, 16))
        self.label_25.setObjectName("label_25")
        self.list_x_test_2 = QtWidgets.QTableWidget(self.tab_4)
        self.list_x_test_2.setGeometry(QtCore.QRect(330, 220, 221, 111))
        self.list_x_test_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_x_test_2.setObjectName("list_x_test_2")
        self.list_x_test_2.setColumnCount(0)
        self.list_x_test_2.setRowCount(0)
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(330, 200, 81, 16))
        self.label_12.setObjectName("label_12")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 151, 16))
        self.label_5.setObjectName("label_5")
        self.list_y_train_2 = QtWidgets.QTableWidget(self.tab_4)
        self.list_y_train_2.setGeometry(QtCore.QRect(620, 50, 221, 111))
        self.list_y_train_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_y_train_2.setObjectName("list_y_train_2")
        self.list_y_train_2.setColumnCount(0)
        self.list_y_train_2.setRowCount(0)
        self.label_28 = QtWidgets.QLabel(self.tab_4)
        self.label_28.setGeometry(QtCore.QRect(620, 30, 71, 16))
        self.label_28.setObjectName("label_28")
        self.verigoster_4 = QtWidgets.QTableWidget(self.tab_4)
        self.verigoster_4.setGeometry(QtCore.QRect(10, 30, 291, 461))
        self.verigoster_4.setStyleSheet("background-color: rgb(186, 186, 186);")
        self.verigoster_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.verigoster_4.setObjectName("verigoster_4")
        self.verigoster_4.setColumnCount(0)
        self.verigoster_4.setRowCount(0)
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(330, 30, 91, 16))
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.list_y_test_3 = QtWidgets.QTableWidget(self.tab_6)
        self.list_y_test_3.setGeometry(QtCore.QRect(630, 220, 221, 111))
        self.list_y_test_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_y_test_3.setObjectName("list_y_test_3")
        self.list_y_test_3.setColumnCount(0)
        self.list_y_test_3.setRowCount(0)
        self.list_x_train_3 = QtWidgets.QTableWidget(self.tab_6)
        self.list_x_train_3.setGeometry(QtCore.QRect(340, 50, 221, 111))
        self.list_x_train_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_x_train_3.setObjectName("list_x_train_3")
        self.list_x_train_3.setColumnCount(0)
        self.list_x_train_3.setRowCount(0)
        self.label_26 = QtWidgets.QLabel(self.tab_6)
        self.label_26.setGeometry(QtCore.QRect(640, 200, 71, 16))
        self.label_26.setObjectName("label_26")
        self.list_x_test_3 = QtWidgets.QTableWidget(self.tab_6)
        self.list_x_test_3.setGeometry(QtCore.QRect(340, 220, 221, 111))
        self.list_x_test_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_x_test_3.setObjectName("list_x_test_3")
        self.list_x_test_3.setColumnCount(0)
        self.list_x_test_3.setRowCount(0)
        self.label_13 = QtWidgets.QLabel(self.tab_6)
        self.label_13.setGeometry(QtCore.QRect(340, 200, 81, 16))
        self.label_13.setObjectName("label_13")
        self.label_6 = QtWidgets.QLabel(self.tab_6)
        self.label_6.setGeometry(QtCore.QRect(30, 10, 151, 16))
        self.label_6.setObjectName("label_6")
        self.list_y_train_3 = QtWidgets.QTableWidget(self.tab_6)
        self.list_y_train_3.setGeometry(QtCore.QRect(630, 50, 221, 111))
        self.list_y_train_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_y_train_3.setObjectName("list_y_train_3")
        self.list_y_train_3.setColumnCount(0)
        self.list_y_train_3.setRowCount(0)
        self.label_29 = QtWidgets.QLabel(self.tab_6)
        self.label_29.setGeometry(QtCore.QRect(630, 30, 71, 16))
        self.label_29.setObjectName("label_29")
        self.verigoster_5 = QtWidgets.QTableWidget(self.tab_6)
        self.verigoster_5.setGeometry(QtCore.QRect(20, 30, 291, 461))
        self.verigoster_5.setStyleSheet("background-color: rgb(186, 186, 186);")
        self.verigoster_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.verigoster_5.setObjectName("verigoster_5")
        self.verigoster_5.setColumnCount(0)
        self.verigoster_5.setRowCount(0)
        self.label_19 = QtWidgets.QLabel(self.tab_6)
        self.label_19.setGeometry(QtCore.QRect(340, 30, 91, 16))
        self.label_19.setObjectName("label_19")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.btnveribol_2 = QtWidgets.QPushButton(self.tab_7)
        self.btnveribol_2.setGeometry(QtCore.QRect(400, 30, 361, 31))
        self.btnveribol_2.setStyleSheet("")
        self.btnveribol_2.setObjectName("btnveribol_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox.setGeometry(QtCore.QRect(30, 90, 231, 121))
        self.groupBox.setObjectName("groupBox")
        self.lblr2sonuc_3 = QtWidgets.QLabel(self.groupBox)
        self.lblr2sonuc_3.setGeometry(QtCore.QRect(120, 90, 91, 16))
        self.lblr2sonuc_3.setText("")
        self.lblr2sonuc_3.setObjectName("lblr2sonuc_3")
        self.lblr2sonuc = QtWidgets.QLabel(self.groupBox)
        self.lblr2sonuc.setGeometry(QtCore.QRect(120, 20, 91, 16))
        self.lblr2sonuc.setText("")
        self.lblr2sonuc.setObjectName("lblr2sonuc")
        self.lblr2sonuc_2 = QtWidgets.QLabel(self.groupBox)
        self.lblr2sonuc_2.setGeometry(QtCore.QRect(120, 50, 91, 16))
        self.lblr2sonuc_2.setText("")
        self.lblr2sonuc_2.setObjectName("lblr2sonuc_2")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_17.setObjectName("label_17")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_18.setObjectName("label_18")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 90, 231, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lblr2sonuc_4 = QtWidgets.QLabel(self.groupBox_2)
        self.lblr2sonuc_4.setGeometry(QtCore.QRect(120, 90, 91, 16))
        self.lblr2sonuc_4.setText("")
        self.lblr2sonuc_4.setObjectName("lblr2sonuc_4")
        self.lblr2sonuc_5 = QtWidgets.QLabel(self.groupBox_2)
        self.lblr2sonuc_5.setGeometry(QtCore.QRect(120, 20, 91, 16))
        self.lblr2sonuc_5.setText("")
        self.lblr2sonuc_5.setObjectName("lblr2sonuc_5")
        self.lblr2sonuc_6 = QtWidgets.QLabel(self.groupBox_2)
        self.lblr2sonuc_6.setGeometry(QtCore.QRect(120, 50, 91, 16))
        self.lblr2sonuc_6.setText("")
        self.lblr2sonuc_6.setObjectName("lblr2sonuc_6")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_22.setObjectName("label_22")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_4.setGeometry(QtCore.QRect(530, 90, 231, 121))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lblr2sonuc_10 = QtWidgets.QLabel(self.groupBox_4)
        self.lblr2sonuc_10.setGeometry(QtCore.QRect(120, 90, 91, 16))
        self.lblr2sonuc_10.setText("")
        self.lblr2sonuc_10.setObjectName("lblr2sonuc_10")
        self.lblr2sonuc_11 = QtWidgets.QLabel(self.groupBox_4)
        self.lblr2sonuc_11.setGeometry(QtCore.QRect(120, 20, 91, 16))
        self.lblr2sonuc_11.setText("")
        self.lblr2sonuc_11.setObjectName("lblr2sonuc_11")
        self.lblr2sonuc_12 = QtWidgets.QLabel(self.groupBox_4)
        self.lblr2sonuc_12.setGeometry(QtCore.QRect(120, 50, 91, 16))
        self.lblr2sonuc_12.setText("")
        self.lblr2sonuc_12.setObjectName("lblr2sonuc_12")
        self.label_32 = QtWidgets.QLabel(self.groupBox_4)
        self.label_32.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.groupBox_4)
        self.label_34.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_34.setObjectName("label_34")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 290, 231, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lblr2sonuc_7 = QtWidgets.QLabel(self.groupBox_3)
        self.lblr2sonuc_7.setGeometry(QtCore.QRect(120, 90, 91, 16))
        self.lblr2sonuc_7.setText("")
        self.lblr2sonuc_7.setObjectName("lblr2sonuc_7")
        self.lblr2sonuc_8 = QtWidgets.QLabel(self.groupBox_3)
        self.lblr2sonuc_8.setGeometry(QtCore.QRect(120, 20, 91, 16))
        self.lblr2sonuc_8.setText("")
        self.lblr2sonuc_8.setObjectName("lblr2sonuc_8")
        self.lblr2sonuc_9 = QtWidgets.QLabel(self.groupBox_3)
        self.lblr2sonuc_9.setGeometry(QtCore.QRect(120, 50, 91, 16))
        self.lblr2sonuc_9.setText("")
        self.lblr2sonuc_9.setObjectName("lblr2sonuc_9")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_23.setObjectName("label_23")
        self.label_30 = QtWidgets.QLabel(self.groupBox_3)
        self.label_30.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.groupBox_3)
        self.label_31.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_31.setObjectName("label_31")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_5.setGeometry(QtCore.QRect(290, 290, 231, 121))
        self.groupBox_5.setObjectName("groupBox_5")
        self.lblr2sonuc_13 = QtWidgets.QLabel(self.groupBox_5)
        self.lblr2sonuc_13.setGeometry(QtCore.QRect(120, 90, 91, 16))
        self.lblr2sonuc_13.setText("")
        self.lblr2sonuc_13.setObjectName("lblr2sonuc_13")
        self.lblr2sonuc_14 = QtWidgets.QLabel(self.groupBox_5)
        self.lblr2sonuc_14.setGeometry(QtCore.QRect(120, 20, 91, 16))
        self.lblr2sonuc_14.setText("")
        self.lblr2sonuc_14.setObjectName("lblr2sonuc_14")
        self.lblr2sonuc_15 = QtWidgets.QLabel(self.groupBox_5)
        self.lblr2sonuc_15.setGeometry(QtCore.QRect(120, 50, 91, 16))
        self.lblr2sonuc_15.setText("")
        self.lblr2sonuc_15.setObjectName("lblr2sonuc_15")
        self.label_35 = QtWidgets.QLabel(self.groupBox_5)
        self.label_35.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.groupBox_5)
        self.label_36.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_5)
        self.label_37.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_37.setObjectName("label_37")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_6.setGeometry(QtCore.QRect(540, 290, 231, 121))
        self.groupBox_6.setObjectName("groupBox_6")
        self.lblr2sonuc_16 = QtWidgets.QLabel(self.groupBox_6)
        self.lblr2sonuc_16.setGeometry(QtCore.QRect(120, 90, 91, 16))
        self.lblr2sonuc_16.setText("")
        self.lblr2sonuc_16.setObjectName("lblr2sonuc_16")
        self.lblr2sonuc_17 = QtWidgets.QLabel(self.groupBox_6)
        self.lblr2sonuc_17.setGeometry(QtCore.QRect(120, 20, 91, 16))
        self.lblr2sonuc_17.setText("")
        self.lblr2sonuc_17.setObjectName("lblr2sonuc_17")
        self.lblr2sonuc_18 = QtWidgets.QLabel(self.groupBox_6)
        self.lblr2sonuc_18.setGeometry(QtCore.QRect(120, 50, 91, 16))
        self.lblr2sonuc_18.setText("")
        self.lblr2sonuc_18.setObjectName("lblr2sonuc_18")
        self.label_38 = QtWidgets.QLabel(self.groupBox_6)
        self.label_38.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_6)
        self.label_39.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_6)
        self.label_40.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_40.setObjectName("label_40")
        self.tabWidget.addTab(self.tab_7, "")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "BALTİC VERİSİ"))
        self.btnyukle.setText(_translate("MainWindow", "VERİLERİ YÜKLE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "verileri yükle"))
        self.btnyukle_2.setText(_translate("MainWindow", "VERİLERİ AYLIK SINIFLANDIR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "VERİLERİ SINIFLANDIR AYLIK"))
        self.btnveribol.setText(_translate("MainWindow", "VERİLERİ YILLARA BÖL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "VERİLERİ YIL OLARAK AYIR"))
        self.label_27.setText(_translate("MainWindow", "Y  T r a i n"))
        self.label_24.setText(_translate("MainWindow", "Y  T e s t"))
        self.label_11.setText(_translate("MainWindow", "X  T e s t"))
        self.label_14.setText(_translate("MainWindow", "X  T r a i n"))
        self.label_4.setText(_translate("MainWindow", "YIL AY VERİLERİ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "T-1 YILINA AİT VERİLER(2015)"))
        self.label_25.setText(_translate("MainWindow", "Y  T e s t"))
        self.label_12.setText(_translate("MainWindow", "X  T e s t"))
        self.label_5.setText(_translate("MainWindow", "YIL AY VERİLERİ"))
        self.label_28.setText(_translate("MainWindow", "Y  T r a i n"))
        self.label_15.setText(_translate("MainWindow", "X  T r a i n"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "T YILINA AİT VERİLER(2016)"))
        self.label_26.setText(_translate("MainWindow", "Y  T e s t"))
        self.label_13.setText(_translate("MainWindow", "X  T e s t"))
        self.label_6.setText(_translate("MainWindow", "YIL AY VERİLERİ"))
        self.label_29.setText(_translate("MainWindow", "Y  T r a i n"))
        self.label_19.setText(_translate("MainWindow", "X  T r a i n"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "T+1 YILINA AİT VERİLER(2017)"))
        self.btnveribol_2.setText(_translate("MainWindow", "R2-MAE-RMSE UYGULA"))
        self.groupBox.setTitle(_translate("MainWindow", "2017 yılına ait hesaplamalar"))
        self.label_17.setText(_translate("MainWindow", "MAE SONUCU :"))
        self.label_16.setText(_translate("MainWindow", "R2 SONUCU :"))
        self.label_18.setText(_translate("MainWindow", "RMSE SONUCU :"))
        self.groupBox_2.setTitle(_translate("MainWindow", "2016 yılına ait hesaplamalar"))
        self.label_20.setText(_translate("MainWindow", "MAE SONUCU :"))
        self.label_21.setText(_translate("MainWindow", "R2 SONUCU :"))
        self.label_22.setText(_translate("MainWindow", "RMSE SONUCU :"))
        self.groupBox_4.setTitle(_translate("MainWindow", "2015 yılına ait hesaplamalar"))
        self.label_32.setText(_translate("MainWindow", "MAE SONUCU :"))
        self.label_33.setText(_translate("MainWindow", "R2 SONUCU :"))
        self.label_34.setText(_translate("MainWindow", "RMSE SONUCU :"))
        self.groupBox_3.setTitle(_translate("MainWindow", "t-1 ile t yılına ait hesaplamalar"))
        self.label_23.setText(_translate("MainWindow", "MAE SONUCU :"))
        self.label_30.setText(_translate("MainWindow", "R2 SONUCU :"))
        self.label_31.setText(_translate("MainWindow", "RMSE SONUCU :"))
        self.groupBox_5.setTitle(_translate("MainWindow", "t il t+1 yılına ait hesaplamalar"))
        self.label_35.setText(_translate("MainWindow", "MAE SONUCU :"))
        self.label_36.setText(_translate("MainWindow", "R2 SONUCU :"))
        self.label_37.setText(_translate("MainWindow", "RMSE SONUCU :"))
        self.groupBox_6.setTitle(_translate("MainWindow", "t-1 ile t+1 yılına ait hesaplamalar"))
        self.label_38.setText(_translate("MainWindow", "MAE SONUCU :"))
        self.label_39.setText(_translate("MainWindow", "R2 SONUCU :"))
        self.label_40.setText(_translate("MainWindow", "RMSE SONUCU :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "SONUCLAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

